// core/src/components/fields/text-field/text-field-component.tsx
import { Component, Method, State, } from '@stencil/core';
import { ContentField } from '../../../models/content-models';

@Component({
    tag: 'aly-text-field',
    styleUrl: 'text-field-component.scss',
    shadow: true
})
export class TextFieldComponent {

    @State()
    field: ContentField<string>;

    @Method()
    async setField(field: ContentField<string>) {
        this.field = field;
    }

    render() {
        return this.field.value;
    }
}

// angular/projects/alaska-contents/src/lib/components/fields/text-field/text-field.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { ContentField } from '@alaska-project/contents-core/dist/types/models/content-models';

@Component({
  selector: 'aly-text-field',
  templateUrl: './text-field.component.html',
  styleUrls: ['./text-field.component.scss']
})
export class TextFieldComponent implements OnInit {

  @Input()
  field: ContentField<any>;

  constructor() { }

  ngOnInit() {
  }

}

<p>
  text-field works!
</p>
