// angular/projects/alaska-contents/src/lib/components/fields/html-field-editor/html-field-editor.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'aly-html-field-editor',
  templateUrl: './html-field-editor.component.html',
  styleUrls: ['./html-field-editor.component.scss']
})
export class HtmlFieldEditorComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<p>
  html-field-editor works!
</p>

// core/src/components/fields/html-field-editor/html-field-editor-component.tsx
import { Component, h, Prop } from '@stencil/core';
import { FieldData } from '../../../models/content-models';

@Component({
    tag: 'aly-html-field-editor',
    styleUrl: 'html-field-editor-component.scss',
    shadow: true
})
export class HtmlFieldEditorComponent {

    @Prop()
    field: FieldData<any>;

    render() {
        return (this.field  ? 
            <span class="field">{this.field.data.value}</span> : 
            undefined);
    }
}
