// angular/projects/alaska-contents/src/lib/components/fields/content-field/content-field.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'aly-content-field',
  templateUrl: './content-field.component.html',
  styleUrls: ['./content-field.component.scss']
})
export class ContentFieldComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<aly-content-field-default *ngIf="mode === 'Default'" [field]="field"></aly-content-field-default>
<aly-content-field-editor *ngIf="mode === 'Editing'" [field]="field"></aly-content-field-editor>

// core/src/components/fields/content-field/content-field-component.tsx
import { Component, Method, State, h } from '@stencil/core';
import { ContentField } from '../../../models/content-models';
import { ContentMode } from '../../../models/component-models';

@Component({
    tag: 'aly-content-field',
    styleUrl: 'content-field-component.scss',
    shadow: true
})
export class ContentFieldComponent {

    @State()
    field: ContentField<any>;

    @Method()
    async setField(field: ContentField<any>) {
        this.field = field;
    }

    @State()
    mode: ContentMode = 'Default';

    @Method()
    async setMode(mode: ContentMode) {
        this.mode = mode;
    }

    render() {
        if (!this.field) {
            return undefined;
        }

        return (<div>
            <aly-content-field-default hidden={this.mode !== 'Default'} ref={(el) => el.setField(this.field)}></aly-content-field-default>
            <aly-content-field-editor hidden={this.mode !== 'Editing'} ref={(el) => el.setField(this.field)}></aly-content-field-editor>
        </div>
        );
    }
}
